USE PRACTICA1;
-- INSERTAR DATOS EN HABITACION --

LOAD DATA LOCAL INFILE 'C:/Users/OMEN/Documents/CargasMysql/CSV_P1_BASES2/Habitaciones.csv'
INTO TABLE HABITACION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(idHabitacion, habitacion);