USE PRACTICA1;
-- INSERTAR DATOS EN HABITACION --

LOAD DATA LOCAL INFILE 'C:/Users/OMEN/OneDrive/Documentos/Bases2/Practica1Docs/CSV/Habitaciones.csv'
INTO TABLE HABITACION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(idHabitacion, habitacion);

SELECT * FROM HABITACION;

-- INSERTAR DATOS EN PACIENTES

LOAD DATA LOCAL INFILE 'C:/Users/OMEN/OneDrive/Documentos/Bases2/Practica1Docs/CSV/Pacientes.csv'
INTO TABLE PACIENTE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(idPaciente, edad, genero);

SELECT * FROM PACIENTE;

-- INSERTAR DATOS EN LOG_ACTIVIDADES 1 --

LOAD DATA LOCAL INFILE 'C:/Users/OMEN/OneDrive/Documentos/Bases2/Practica1Docs/CSV/LogActividades1.csv'
INTO TABLE LOG_ACTIVIDAD
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(timestampx, actividad, idHabitacion, idPaciente);

SELECT * FROM LOG_ACTIVIDAD;

-- INSERTAR DATOS EN LOG_ACTIVIDADES 2 --

LOAD DATA LOCAL INFILE 'C:/Users/OMEN/OneDrive/Documentos/Bases2/Practica1Docs/CSV/LogActividades2.csv'
INTO TABLE LOG_ACTIVIDAD
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(timestampx, actividad, idHabitacion, idPaciente);

SELECT * FROM LOG_ACTIVIDAD;

-- INSERTAR DATOS EN LOG_HABITACION --

LOAD DATA LOCAL INFILE 'C:/Users/OMEN/OneDrive/Documentos/Bases2/Practica1Docs/CSV/LogHabitacion.csv'
INTO TABLE LOG_HABITACION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(idHabitacion, timestampx, statusx);

SELECT * FROM LOG_HABITACION;